-- Adds NOTES column for admin seat notes (idempotent).
DO
BEGIN
  DECLARE v_count INTEGER;
  SELECT COUNT(*) INTO v_count
  FROM SYS.TABLE_COLUMNS
  WHERE SCHEMA_NAME = 'ITIL_EXAM'
    AND TABLE_NAME = 'ACCESS_CODES'
    AND COLUMN_NAME = 'NOTES';

  IF :v_count = 0 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE "ITIL_EXAM"."ACCESS_CODES" ADD ("NOTES" NVARCHAR(500))';
  END IF;
END;
