-- Adds practice-mode controls and soft-delete support for access codes.
-- Idempotent for SAP HANA Cloud. Runs against CURRENT_SCHEMA.
DO
BEGIN
  DECLARE col_count INTEGER;
  DECLARE schema_name NVARCHAR(256) := CURRENT_SCHEMA;

  SELECT COUNT(*) INTO col_count FROM SYS.TABLE_COLUMNS
   WHERE SCHEMA_NAME = :schema_name AND TABLE_NAME = 'QUESTION_SETS' AND COLUMN_NAME = 'EXAM_MODE';
  IF :col_count = 0 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE "' || :schema_name || '"."QUESTION_SETS" ADD ("EXAM_MODE" NVARCHAR(20) DEFAULT ''GRADED'' NOT NULL)';
  END IF;

  SELECT COUNT(*) INTO col_count FROM SYS.TABLE_COLUMNS
   WHERE SCHEMA_NAME = :schema_name AND TABLE_NAME = 'QUESTION_SETS' AND COLUMN_NAME = 'SHOW_CORRECT_ANSWERS';
  IF :col_count = 0 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE "' || :schema_name || '"."QUESTION_SETS" ADD ("SHOW_CORRECT_ANSWERS" BOOLEAN DEFAULT FALSE NOT NULL)';
  END IF;

  SELECT COUNT(*) INTO col_count FROM SYS.TABLE_COLUMNS
   WHERE SCHEMA_NAME = :schema_name AND TABLE_NAME = 'QUESTION_SETS' AND COLUMN_NAME = 'COUNTS_TOWARD_RESULTS';
  IF :col_count = 0 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE "' || :schema_name || '"."QUESTION_SETS" ADD ("COUNTS_TOWARD_RESULTS" BOOLEAN DEFAULT TRUE NOT NULL)';
  END IF;

  EXECUTE IMMEDIATE '
    UPDATE "' || :schema_name || '"."QUESTION_SETS"
       SET "EXAM_MODE" = COALESCE(NULLIF("EXAM_MODE", ''''), ''GRADED''),
           "SHOW_CORRECT_ANSWERS" = CASE WHEN "EXAM_MODE" = ''PRACTICE'' THEN TRUE ELSE COALESCE("SHOW_CORRECT_ANSWERS", FALSE) END,
           "COUNTS_TOWARD_RESULTS" = CASE WHEN "EXAM_MODE" = ''PRACTICE'' THEN FALSE ELSE COALESCE("COUNTS_TOWARD_RESULTS", TRUE) END
  ';

  SELECT COUNT(*) INTO col_count FROM SYS.TABLE_COLUMNS
   WHERE SCHEMA_NAME = :schema_name AND TABLE_NAME = 'ACCESS_CODES' AND COLUMN_NAME = 'DELETED_AT';
  IF :col_count = 0 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE "' || :schema_name || '"."ACCESS_CODES" ADD ("DELETED_AT" TIMESTAMP NULL)';
  END IF;

  SELECT COUNT(*) INTO col_count FROM SYS.TABLE_COLUMNS
   WHERE SCHEMA_NAME = :schema_name AND TABLE_NAME = 'ACCESS_CODES' AND COLUMN_NAME = 'DELETED_BY';
  IF :col_count = 0 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE "' || :schema_name || '"."ACCESS_CODES" ADD ("DELETED_BY" NVARCHAR(120) NULL)';
  END IF;
END;
