-- Run after SET SCHEMA <target_schema>. All object references are intentionally
-- unqualified so the migration works with HANA_SCHEMA values other than ITIL_EXAM.
DO
BEGIN
  DECLARE sso_v2_exists INTEGER;
  DECLARE rate_exists INTEGER;
  DECLARE mutex_exists INTEGER;

  SELECT COUNT(*) INTO sso_v2_exists FROM SYS.TABLES
   WHERE SCHEMA_NAME = CURRENT_SCHEMA AND TABLE_NAME = 'ADMIN_SSO_SESSIONS_V2';
  IF :sso_v2_exists = 0 THEN
    EXECUTE IMMEDIATE '
      CREATE TABLE "ADMIN_SSO_SESSIONS_V2" (
        "SESSION_ID" NVARCHAR(128) PRIMARY KEY,
        "TOKEN_CIPHERTEXT" NCLOB NOT NULL,
        "TOKEN_IV" NVARCHAR(64) NOT NULL,
        "TOKEN_TAG" NVARCHAR(64) NOT NULL,
        "SUBJECT" NVARCHAR(255),
        "ROLE_NAME" NVARCHAR(40) NOT NULL,
        "ISSUED_AT_MS" BIGINT NOT NULL,
        "EXPIRES_AT_MS" BIGINT NOT NULL,
        "CREATED_AT" TIMESTAMP DEFAULT CURRENT_UTCTIMESTAMP NOT NULL,
        "LAST_SEEN_AT" TIMESTAMP DEFAULT CURRENT_UTCTIMESTAMP NOT NULL
      )';
  END IF;

  SELECT COUNT(*) INTO rate_exists FROM SYS.TABLES
   WHERE SCHEMA_NAME = CURRENT_SCHEMA AND TABLE_NAME = 'APP_RATE_LIMITS';
  IF :rate_exists = 0 THEN
    EXECUTE IMMEDIATE '
      CREATE TABLE "APP_RATE_LIMITS" (
        "BUCKET_KEY" NVARCHAR(64) PRIMARY KEY,
        "HIT_COUNT" INTEGER NOT NULL,
        "RESET_AT_MS" BIGINT NOT NULL,
        "UPDATED_AT" TIMESTAMP DEFAULT CURRENT_UTCTIMESTAMP NOT NULL
      )';
  END IF;

  SELECT COUNT(*) INTO mutex_exists FROM SYS.TABLES
   WHERE SCHEMA_NAME = CURRENT_SCHEMA AND TABLE_NAME = 'APP_MUTEX';
  IF :mutex_exists = 0 THEN
    EXECUTE IMMEDIATE '
      CREATE TABLE "APP_MUTEX" (
        "LOCK_NAME" NVARCHAR(80) PRIMARY KEY,
        "UPDATED_AT" TIMESTAMP DEFAULT CURRENT_UTCTIMESTAMP NOT NULL
      )';
  END IF;

  MERGE INTO "APP_MUTEX" AS target
  USING (SELECT 'question_sets' AS LOCK_NAME FROM DUMMY) AS source
     ON target."LOCK_NAME" = source.LOCK_NAME
  WHEN NOT MATCHED THEN INSERT ("LOCK_NAME", "UPDATED_AT")
    VALUES (source.LOCK_NAME, CURRENT_UTCTIMESTAMP);
END;