-- Run after SET SCHEMA <target_schema>.
DO
BEGIN
  DECLARE sso_v3_exists INTEGER;

  SELECT COUNT(*) INTO sso_v3_exists
    FROM SYS.TABLES
   WHERE SCHEMA_NAME = CURRENT_SCHEMA
     AND TABLE_NAME = 'ADMIN_SSO_SESSIONS_V3';

  IF :sso_v3_exists = 0 THEN
    EXECUTE IMMEDIATE '
      CREATE TABLE "ADMIN_SSO_SESSIONS_V3" (
        "SESSION_ID" NVARCHAR(128) PRIMARY KEY,
        "KEY_ID" NVARCHAR(64) NOT NULL,
        "TOKEN_CIPHERTEXT" NCLOB NOT NULL,
        "TOKEN_IV" NVARCHAR(64) NOT NULL,
        "TOKEN_TAG" NVARCHAR(64) NOT NULL,
        "SUBJECT" NVARCHAR(255),
        "ROLE_NAME" NVARCHAR(40) NOT NULL,
        "ISSUED_AT_MS" BIGINT NOT NULL,
        "EXPIRES_AT_MS" BIGINT NOT NULL,
        "CREATED_AT" TIMESTAMP DEFAULT CURRENT_UTCTIMESTAMP NOT NULL,
        "LAST_SEEN_AT" TIMESTAMP DEFAULT CURRENT_UTCTIMESTAMP NOT NULL
      )';
  END IF;
END;