DO
BEGIN
  DECLARE table_exists INTEGER;

  SELECT COUNT(*)
    INTO table_exists
    FROM SYS.TABLES
   WHERE SCHEMA_NAME = 'ITIL_EXAM'
     AND TABLE_NAME = 'EXAM_QUESTIONS';

  IF :table_exists = 0 THEN
    EXECUTE IMMEDIATE '
      CREATE TABLE "ITIL_EXAM"."EXAM_QUESTIONS" (
        "QUESTION_INDEX" INTEGER PRIMARY KEY,
        "STEM" NCLOB NOT NULL,
        "NOTE" NCLOB NULL,
        "OPTS_JSON" NCLOB NOT NULL,
        "ANSWER_JSON" NCLOB NOT NULL,
        "MULTI" BOOLEAN DEFAULT FALSE NOT NULL,
        "UPDATED_AT" TIMESTAMP DEFAULT CURRENT_UTCTIMESTAMP NOT NULL
      )
    ';
  END IF;
END;
