DO
BEGIN
  DECLARE table_count INTEGER := 0;

  SELECT COUNT(*) INTO table_count
    FROM TABLES
   WHERE SCHEMA_NAME = CURRENT_SCHEMA
     AND TABLE_NAME = 'APP_SETTINGS';

  IF :table_count = 0 THEN
    EXEC 'CREATE COLUMN TABLE APP_SETTINGS (
      SETTING_KEY NVARCHAR(100) PRIMARY KEY,
      SETTING_VALUE NVARCHAR(5000),
      UPDATED_AT TIMESTAMP DEFAULT CURRENT_UTCTIMESTAMP
    )';
  END IF;
END;

DO
BEGIN
  DECLARE setting_count INTEGER := 0;

  SELECT COUNT(*) INTO setting_count
    FROM APP_SETTINGS
   WHERE SETTING_KEY = 'EXAMS_ENABLED';

  IF :setting_count = 0 THEN
    INSERT INTO APP_SETTINGS (SETTING_KEY, SETTING_VALUE, UPDATED_AT)
    VALUES ('EXAMS_ENABLED', 'true', CURRENT_UTCTIMESTAMP);
  END IF;
END;
