-- Adds question set versioning metadata for draft/publish/archive and import tracking.
DO
BEGIN
  DECLARE schema_name NVARCHAR(256) := CURRENT_SCHEMA;
  DECLARE col_count INTEGER;

  SELECT COUNT(*) INTO col_count FROM SYS.TABLE_COLUMNS
   WHERE SCHEMA_NAME = :schema_name AND TABLE_NAME = 'QUESTION_SETS' AND COLUMN_NAME = 'VERSION_GROUP_ID';
  IF :col_count = 0 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE "' || :schema_name || '"."QUESTION_SETS" ADD ("VERSION_GROUP_ID" BIGINT NULL)';
  END IF;

  SELECT COUNT(*) INTO col_count FROM SYS.TABLE_COLUMNS
   WHERE SCHEMA_NAME = :schema_name AND TABLE_NAME = 'QUESTION_SETS' AND COLUMN_NAME = 'VERSION_NUMBER';
  IF :col_count = 0 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE "' || :schema_name || '"."QUESTION_SETS" ADD ("VERSION_NUMBER" INTEGER DEFAULT 1 NOT NULL)';
  END IF;

  SELECT COUNT(*) INTO col_count FROM SYS.TABLE_COLUMNS
   WHERE SCHEMA_NAME = :schema_name AND TABLE_NAME = 'QUESTION_SETS' AND COLUMN_NAME = 'LIFECYCLE_STATUS';
  IF :col_count = 0 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE "' || :schema_name || '"."QUESTION_SETS" ADD ("LIFECYCLE_STATUS" NVARCHAR(20) DEFAULT ''PUBLISHED'' NOT NULL)';
  END IF;

  SELECT COUNT(*) INTO col_count FROM SYS.TABLE_COLUMNS
   WHERE SCHEMA_NAME = :schema_name AND TABLE_NAME = 'QUESTION_SETS' AND COLUMN_NAME = 'PARENT_QUESTION_SET_ID';
  IF :col_count = 0 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE "' || :schema_name || '"."QUESTION_SETS" ADD ("PARENT_QUESTION_SET_ID" BIGINT NULL)';
  END IF;

  SELECT COUNT(*) INTO col_count FROM SYS.TABLE_COLUMNS
   WHERE SCHEMA_NAME = :schema_name AND TABLE_NAME = 'QUESTION_SETS' AND COLUMN_NAME = 'IMPORT_SOURCE';
  IF :col_count = 0 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE "' || :schema_name || '"."QUESTION_SETS" ADD ("IMPORT_SOURCE" NVARCHAR(255) NULL)';
  END IF;

  EXECUTE IMMEDIATE '
    UPDATE "' || :schema_name || '"."QUESTION_SETS"
       SET "VERSION_GROUP_ID" = COALESCE("VERSION_GROUP_ID", "QUESTION_SET_ID"),
           "VERSION_NUMBER" = COALESCE("VERSION_NUMBER", 1),
           "LIFECYCLE_STATUS" = COALESCE(NULLIF("LIFECYCLE_STATUS", ''''), CASE WHEN "IS_ACTIVE" = TRUE THEN ''PUBLISHED'' ELSE ''ARCHIVED'' END),
           "IMPORT_SOURCE" = COALESCE("IMPORT_SOURCE", ''manual''),
           "UPDATED_AT" = CURRENT_UTCTIMESTAMP
  ';
END;
